#!/bin/bash
docker run --rm --name maven --privileged \
 -v /usr/bin/docker:/usr/bin/docker \
 -v /var/run/docker.sock:/var/run/docker.sock \
 -v ~/.m2:/root/.m2 \
 -v $(pwd)/server:/api \
 -w /api maven:3.9.9-eclipse-temurin-23 \
 mvn "$@"