#!/bin/bash
docker run --rm --name maven --privileged \
 -v /usr/bin/docker:/usr/bin/docker \
 -v /var/run/docker.sock:/var/run/docker.sock \
 -v ./.docker/.volumes/maven/repository:/root/.m2/repository \
 -v $(pwd)/server:/api \
 -w /api maven:3.9.9-eclipse-temurin-21 \
 mvn "$@"