services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:jammy
    container_name: granas-development
    privileged: true
    restart: unless-stopped
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEBIAN_FRONTEND=noninteractive
    volumes:
      - ../.docker/configurations/maven/settings.xml:/home/vscode/.m2/settings.xml:ro
      - ..:/workspace/development:cached
      - ~/.ssh:/home/vscode/.ssh:ro
    entrypoint: "sleep infinity"
